# Generated by Django 4.2.3 on 2023-08-01 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('sid', models.IntegerField(primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=20)),
                ('smarks', models.FloatField()),
            ],
        ),
    ]
